### ISSUE TITLE
Should strings be converted to text fields?

### ISSUE THREAD

**Issue by nodesocket** [drone/sqlgen#1]
Should `strings` really be converted to `text` fields? `text` types are notoriously slow, and I believe might not be able to use indexes. `varchar()` might be a better choice.

**Comment by bradrydzewski** [comment]
the tool defaults to a `sqlite` dialect. If you use `mysql` or `postgres` dialects you'll get different results, for example this is a postgres example:

```sql
CREATE TABLE IF NOT EXISTS issues (
 issue_id       SERIAL PRIMARY KEY 
,issue_number   INTEGER
,issue_title    VARCHAR(512)
,issue_body     VARCHAR(2048)
,issue_assignee VARCHAR(512)
,issue_state    VARCHAR(50)
,issue_labels   BYTEA
);
```

more about dialects: https://github.com/drone/sqlgen#dialects
