### ISSUE TITLE
Why are fields instances seperately before creating the struct type

### ISSUE THREAD

**Issue by GeertJohan** [drone/sqlgen#3]
Given the following code:
```go
func ScanUser(row *sql.Row) (*User, error) {
    var v0 int64
    var v1 string
    var v2 string

    err := row.Scan(
        &v0,
        &v1,
        &v2,
    )
    if err != nil {
        return nil, err
    }

    v := &User{}
    v.ID = v0
    v.Login = v1
    v.Email = v2

    return v, nil
}
```

Why not simplify it to:
```go
func ScanUser(row *sql.Row) (*User, error) {
    v := &User{}

    err := row.Scan(
        &v.ID,
        &v.Login,
        &v.Email,
    )
    if err != nil {
        return nil, err
    }

    return v, nil
}
```

**Comment by bradrydzewski** [comment]
@GeertJohan the generated code needs to handle two important use cases for my projects. First, I need the ability to unmarshal and marshal non-native database types: 

https://github.com/drone/sqlgen/blob/master/demo/issue_sql.go#L10

Second, I need the ability to take a nested Go structure, flatten to a single row on insert or update, and then expand on select:

https://github.com/drone/sqlgen/blob/master/demo/hook_sql.go#L161

The initial algorithms I wrote support both simple and complex use cases. The algorithm does not have any optimizations, at this time, to create simpler output for simpler structures. 

This project expanded upon [scaneo](https://github.com/variadico/scaneo) which does exactly what you are looking for. May be worth checking out if you have simple structs that can be easily mapped to native database types.

**Comment by bradrydzewski** [comment]
I should mention that creating such optimizations wouldn't be too difficult

```Go
var isComplex bool
_, edge := range tree.Edges {
    if edge.Parent != tree {
      isComplex=true
    }
    if edge.Tags != nil && edge.Tags.Encode != "" {
      isComplex=true
    }
}

if isComplex {
  // generate non-optimized functions
} else {
  // generate optimized functions that don't require intermediate vars
}
```

**Comment by GeertJohan** [comment]
Ah that answers my question totally!
I'll close this issue, thanks :smile:

**Comment by bradrydzewski** [comment]
I'm sure at some point I'll write code to optimize for simpler structs. If that is something you'd like to see, let me know, and I can re-name and re-open the issue to track :)
